# Generated by Django 5.0 on 2024-03-05 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_useraccount_user"),
        ("project", "0002_alter_project_account"),
        ("task", "0004_alter_task_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="task.category"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="project.project",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account",
                to="account.useraccount",
            ),
        ),
    ]
