# Generated by Django 5.0 on 2024-03-05 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_useraccount_user"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project",
                to="account.useraccount",
            ),
        ),
    ]
